#!/bin/bash
dnf install pacman arch-install-scripts
pacman-key --init
pacman-key --populate archlinux
pacman -Syyu

hwclock --systohc

localectl --no-convert set-x11-keymap us pc105

sudo cgpt show /dev/mmcblk0 | grep STATE
cgpt add -i 1 -b 17092608 -s 36892624 /dev/mmcblk0
cgpt add -i 13 -b 53985233 -s 1048576 -t kernel -l KERN-D /dev/mmcblk0

mkfs.ext4 /dev/mmcblk0p13

grub-install --boot-directory=/boot /dev/mmcblk0 --force
grub-mkconfig -o /boot/grub/grub.cfg
