#!/bin/bash
# https://github.com/mviereck/x11docker/wiki/How-to-provide-Wayland-socket-to-docker-container
# https://community.kde.org/KWin/Wayland#Starting_a_nested_KWin


# sudo networkmanager nano tmux htop man-db openssh rsync curl aria2 p7zip gptfdisk iputils traceroute pacman-contrib noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra \
# wayland pipewire pipewire-jack \
# plasma-meta plasma sddm plasma-wayland-session xdg-desktop-portal-kde \
# konsole dolphin kate

# sudo networkmanager nano tmux htop man-db openssh rsync curl aria2 p7zip noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra \
# wayland pipewire pipewire-jack \
# plasma-wayland-session xdg-desktop-portal-kde \
# konsole dolphin kate

# paru -Sy --needed --noconfirm htop tmux pipewire-jack noto-fonts plasma plasma-wayland-session xdg-desktop-portal-kde

sudo systemd-nspawn \
-bD $installdir \
--bind /var/cache/pacman/pkg \
--bind $XDG_RUNTIME_DIR \
--bind /dev/shm \
--bind /dev/dri \
--bind /dev/snd \
--bind /run/dbus/system_bus_socket

sudo systemd-nspawn \
-bD $installdir \
--bind /var/cache/pacman/pkg \
--bind $XDG_RUNTIME_DIR/wayland-0 \
--bind $XDG_RUNTIME_DIR/wayland-0.lock \
--bind $XDG_RUNTIME_DIR/pipewire-0 \
--bind $XDG_RUNTIME_DIR/pipewire-0.lock \
--bind $XDG_RUNTIME_DIR/pulse \
--bind /dev/shm \
--bind /dev/dri
Bind=$XDG_RUNTIME_DIR/wayland-0
Bind=$XDG_RUNTIME_DIR/wayland-0.lock
Bind=$XDG_RUNTIME_DIR/pipewire-0
Bind=$XDG_RUNTIME_DIR/pipewire-0.lock
Bind=$XDG_RUNTIME_DIR/pulse

export WAYLAND_DISPLAY=wayland-0
dbus-run-session startplasma-wayland
# dbus-run-session /usr/lib/startplasma-waylandsession

echo $XDG_RUNTIME_DIR
echo $QT_QPA_PLATFORM
echo $XDG_SESSION_TYPE
echo $GDK_BACKEND
echo $CLUTTER_BACKEND
echo $SDL_VIDEODRIVER
echo $WAYLAND_DISPLAY
echo $DISPLAY
# export XDG_RUNTIME_DIR=/run/user/1000
export QT_QPA_PLATFORM=wayland
export XDG_SESSION_TYPE=wayland
export GDK_BACKEND=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export WAYLAND_DISPLAY=wayland-0
export DISPLAY=:1


