#!/bin/bash
yay -S --needed --noconfirm keybase kbfs
# keybase login $username
keybase config set kbfs.mode constrained
# keybase config set kbfs.mode --clear
systemctl --user enable --now keybase
systemctl --user enable --now kbfs
echo 1 > $HOME/kbfs/.kbfs_disable_auto_journals
# echo 0 > $HOME/kbfs/public/25pwn/.kbfs_disable_journal
# keybase fs ps
# keybase fs uploads
# cat #HOME/kbfs/.kbfs_status
# keybase status
