#!/bin/bash
profilename="profile0"
konsave -s "$profilename"
konsave -e "$profilename"
konsave -r "$profilename"

cp -r --preserve=all /home/nicopwn/profile0.knsv $installdir/home/nicopwn

profilename="profile0"
konsave -i "$HOME/$profilename.knsv"
konsave -a "$profilename"
