#!/bin/bash
# sources:
# https://wiki.archlinux.org/title/Snap
# https://snapcraft.io/docs/installing-snap-on-arch-linux

# install squashfuse for use in containers
sudo systemctl enable --now snapd.socket
sudo systemctl enable --now snapd.apparmor
sudo ln -s /var/lib/snapd/snap /snap
sudo snap set system snapshots.automatic.retention=no
sudo snap set system refresh.retain=2
sudo snap set system refresh.timer=null
tee -a "$HOME/bash_profile" << 'EOF'
export PATH="${PATH}:/var/lib/snapd/snap/bin"
EOF
source "$HOME/.bash_profile"

# snap refresh
