#!/bin/bash

size=16G # size of swapfile in bytes
swapfile="/swap/swap0" # location of swapfile
swappiness="1" # swappiness

sudo mkdir /swap
sudo truncate -s 0 $swapfile
sudo chattr +Cm $swapfile
sudo fallocate -l $size $swapfile

sudo chown root:root $swapfile
sudo chmod 0600 $swapfile

sudo sysctl vm.swappiness=$swappiness
echo "vm.swappiness=$swappiness" | sudo tee /etc/sysctl.d/swappiness.conf

sudo mkswap $swapfile
sudo swapon $swapfile

echo "$swapfile none swap defaults" | sudo tee -a /etc/fstab
