#!/bin/bash
# declare -A name=([deps]=dataset1)

declare -A plasma=([deps]="desktopenv")
declare -A konsave=([deps]="pip plasma")
declare -A ytdlp=([deps]="pip")
declare -A pip=([deps]="python")
declare -A python=([deps]="python")

# declare -a list=( konsave ytdlp pip python )
list="plasma konsave ytdlp pip python"
for node in $list
do
declare -n tmpdeps=$node
for dep in ${tmpdeps[deps]}
do
newlist+="$dep $node "
done
done


# printf '%s\n' "$newlist"
tsort << EOF
$newlist
EOF
